title: Sarah Alshehri
logo: /Imgs/Subject 6 1.png
description: Data Scientist
show_downloads: true
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
